电梯的维修问题
* 问题的提出
   复制
* 问题的分析
+ 题目需要一个合适的建造方案来使得公司的利润最大化。按照给定的条件，只需得到一个计算总利润的一般方程，并最大化这个结果。
* 模型的假设
+ 每个电梯的成本为常量，即2万元
+ 在十公里内与十公里外的情况下，地区的销售额为表中所给常量
+ 在每个地区建造维修站的成本为表中所给常量
* 符号说明
+ P 总利润
+ p 每个电梯的利润
+ Ci 在第i个地区建造维修站的成本 
+ Xi 在第i个地区建造维修站, 其中 Xi=1 表示在i地区修建，Xi=0 表示未在该地区修建
+ Si 第i个地区的实际销售量
+ Rij 第i个地区与第j个地区的距离

+ C 为 1x7 矩阵 第i列为Ci
+ X 为 1x7 矩阵 第i列为Xi
+ S 为 1x7 矩阵 第i列为Si
+ R 为 7*7 矩阵 第i行第j列为 Rij
+ B 为一个包含所有X的可能的集合

* 模型的建立
   $\max \limits_{x\subset B}P= p*\sum S - C * X'$
* 模型的求解
+ 鉴于集合B一共包含128个元素，即有128种可选的建造方案，因此，直接遍历所有可能解找出使P最大的X即可。
** 判断一个地区是否为最大销售量
#+BEGIN_SRC octave 
function l = isBT(k, X)
  S = [0 5 12 7 11 18 16 ; ...
       5 0 7 11 4 11 11 ; ...
       12 7 0 14 9 6 13 ; ...
       7 11 14 0 5 12 12 ; ...
       11 4 9 5 0 7 7 ; ...
       18 11 6 12 7 0 12 ; ...
       16 11 13 12 7 12 0 ];
  l = 0;
  nR = Inf;
  for i = 1:7
      if X(i)
        nR = min(S(k, i), nR);
      end
  end
  if nR<=10
    l = 1;
  end
end
#+END_SRC
** 得到各地区的销售量矩阵S
#+BEGIN_SRC octave 
function A = getAmount(X)
  Q = [700 500 1100 800 600 1400 1600  ; ...
       500 400  700 600 450  600  700 ];
  A = zeros(1, 7);
  for i = 1:7
    A(i) = Q(-isBT(i, X)+2, i);
  end
end
#+END_SRC
** 计算总利润
#+BEGIN_SRC octave
function F = getProfit(X)
  C = [240 280 220 260 380 250 200];
  Cost = C * X';
  A = getAmount(X);
  F = 2*sum(A) - Cost;
end
#+END_SRC
** 遍历所有可能方案得到最优解
**** 所有可能方案
#+BEGIN_SRC octave
function p = getAllP(T)
  p = [];
  if T == 1
    p = [0;1];
  else
    P = getAllP(T-1);
    for i = 1:size(P,1)
      p = [ [P(i,:) 1  ; ...
             P(i,:) 0 ]; p];
    end
  end
end
#+END_SRC
**** 得到答案
#+BEGIN_SRC octave
function [n max] = accioAnswer
  P = getAllP(7);
  n = 0;
  max = -Inf;
  for i = 1:size(P, 1)
    pprofit = getProfit(P(i,:));
    if pprofit > max
      n = i;
      max = pprofit;
    end
  end
end
#+END_SRC
* 模型分析
+ 模型具有局限性。模型中的销售量为定值，而实际中，销售量往往为一个随机变量。
* 模型的推广
+ 令题中所给的销售额为销售额的均值，根据经验，可以假定一个销售额的方差矩阵。
+ 计算总利润依然根据均值即题中所给表格数据计算。
+ 假定销售额满足一个正态分布，则易得总利润满足的正态分布为实际各地区销售满足的正态分布之和。
+ 由此，制定一套同时考虑方差与均值的挑选方法。例如，通过均值的平方与方差的比例作为衡量销售额水平的标准，来找出符合市场规律的最佳方案。
+ 实际方案需要通过统计学习该类商品的实际销售情况得出。
* 参考文献
/《数学建模》 陈光亭 裘哲勇/
